name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  continuous_integration_build:
    continue-on-error: true

    name: Testing git multi-branch merge

    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Build
        run: run_test

