name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  continuous_integration_build:
    continue-on-error: true

    name: Testing git multi-branch merge

    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Environment
        run: "dir env:"

      - name: Current Working Directory
        run: "Get-Location"

      - name: Git Path
        run: (get-command git).Path

      - name: Git Version
        run: git --version

      - name: Run Command
        run: run_test
        shell: pwsh